music/urls.py
from . import views
from django.urls import re_path

# defines to which app are the following urls referring to
app_name = 'music'

# re_path contains the url pattern that is a regular expression given as the first argument,
# the view function for the pattern and the name of the url shortcut used in the template
# NOTE: url() function was used in the tutorial, but there was a change in the newer Django versions
urlpatterns = [
    # matching: ../music/
    re_path(r'^$', views.IndexView.as_view(), name='index'),

    # matching: /music/album_no/
    # NOTE: detail view expects primary key, that is why the regex group is named pk
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # matching: /music/album/add/
    re_path(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # matching: /music/album/album_no/
    re_path(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpadte.as_view(), name='album-update'),

    # matching: /music/album/album_no/delete/
    re_path(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # matching: ../music/register/
    re_path(r'^register/$', views.UserFormView.as_view(), name='register'),
]

projektic/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from companies import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    path('stocks/', views.StockList.as_view()),
    re_path(r'^stocks/(?P<pk>[0-9]+)/', views.StockDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

# adding settings (variables in the bottom of the settings.py file)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
# NOTE: the next line in original tutorial was 'from django.core.urlresolvers import reverse'
#       but was changed because of the version difference
from django.urls import reverse


class Album(models.Model):
    """
    Album model that will be translated into album table in our database
    """
    # defining the variables (table columns)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse(viewname='music:detail', kwargs={'pk': self.id})

    def __str__(self):
        """
        :return: string representation of the album
        """
        return "Artist: " + self.artist + " , Title: " + self.album_title


class Song(models.Model):
    """
    Song model that will be translated into song table in our database
    """
    # defining the variables (table columns)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        """
        :return: string representation of the song
        """
        return "Title: " + self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        """
        information about your class
        """
        # what do you want to create?
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import  authenticate, login
from .models import Album
from .forms import UserForm


class IndexView(generic.ListView):
    # defining which template we will be using
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        """
        :return: returns all albums from database
        """
        return Album.objects.all()


class DetailView(generic.DetailView):
    # defining what are we trying to get
    model = Album
    # defining which template we will be using
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    # what you are trying to create
    model = Album
    # mandatory fields
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpadte(UpdateView):
    # what you are trying to update
    model = Album
    # mandatory fields
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    # what you are trying to delete
    model = Album
    # where to go after the album is deleted
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    # what is the blueprint that you are going to use for the form?
    form_class = UserForm
    # html file that the form is going to be included in
    template_name = 'music/registration_form.html'

    def get(self, request):
        """
        going to display a blank form for signing up
        """
        # by the default it has no data, the user is meant to fill the blanks
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        """
        process form data and save our user to the database
        """
        # this time we need to send the post request instead of nothing
        # that is the information that is typed into the form
        # and after submitting all of the data will be stored in this POST data
        # that we will pass to the form and the form itself will validate the data
        form = self.form_class(request.POST)
        if form.is_valid():
            # creates an object from the form without saving it so we can validate even more
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # NOTE: if the username needs changing, change it with user.username = 'New Username'
            #       but if the password needs changing, you must change it with user.set_password('new password')
            user.username = username
            user.set_password(password)
            user.save()

            # returns User object if the credentials are correct
            user = authenticate(username=username, password=password)
            if user:
                # if the user is not banned
                if user.is_active:
                    # logging in
                    login(request, user)
                    # after the login redirect them to the home page
                    return redirect('music:index')

        # if they didn't login, try again
        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{# python code between the following symbols #}
{%  extends 'music/base.html' %}
{# that was indicating that we are using the base template here #}
{# also python comments are written like this #}

{# this is the block used in head for the title in base.html #}
{% block title %}
    <title>Add New Album</title>
{% endblock %}

{# this is the block used in li elements in nav in base.html #}
{# NOTE: fix this, doesn't work #}
{% block add_active %}active{% endblock %}

{# this is the block used after nav in the body in base.html #}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <!-- making a form for creating a new album -->
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {# adding the security token #}
                            {% csrf_token %}
                            {# including the generic form template #}
                            {% include 'music/form-template.html' %}

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%  block title %}
    {% endblock %}
    {# loads the path to our static files #}
    {# also python comments are written like this #}
    {# python code inside the following symbols #}
    {% load staticfiles %}

    <!-- link the bootstrap files -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy"/>
    <!-- link the css stylesheet, loading just the one we need for this template so we don't load the whole thing -->
    <link rel="stylesheet" type="text/css" href="{% static '/music/style.css' %}"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- adding the logo -->
                <a class="navbar-brand" href="{% url 'music:index' %}">Music</a>
            </div>

            <!-- items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block album_active %}{% endblock %}">
                        <a href="#">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"/> Albums
                        </a>
                    </li>
                    <li class="{% block song_active %}{% endblock %}">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"/> Songs
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value=""/>
                    </div>

                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block add_active %}{% endblock %}">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"/> Add-album
                        </a>
                    </li>
                    <li class="{% block logout_active %}{% endblock %}">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"/> Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {# indicating that there will be a block of code next #}
    {% block body %}
    {% endblock %}
</body>
</html>

music/templates/music/detail.html
<!-- the HTML template for music detail page -->

{# python code between the following symbols #}
{%  extends 'music/base.html' %}
{# that was indicating that we are using the base template here #}
{# also python comments are written like this #}

{# this is the block used in head for the title in base.html #}
{% block title %}
    <title>Album Detail</title>
{% endblock %}

{# this is the block used in li elements in nav in base.html #}
{# NOTE: fix this, doesn't work #}
{% block song_active_active %}"active"{% endblock %}

{# this is the block used at the bottom of nav in base.html #}
{% block body %}
    {# python variable in double curly brackets  #}
    <img src="{{ album.album_logo.url }}">
    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    {# python code inside the following symbols #}
    {% if not album.song_set.count > 0 %}
        <p>There are no songs in this album. :(</p>
        {# we must close the python if statement #}
    {% else %}
        <ul>
            {% for song in album.song_set.all %}
            <li>{{ song.song_title }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {# error handler #}
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
{% endblock %}

music/templates/music/form-template.html
{# python code between the following symbols #}
{% for field in form %}
{# also python comments are written like this #}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <!-- adding the labels, label tag is the text for the label -->
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{# we must end the python for loop #}
{% endfor %}

music/templates/music/index.html
<!-- the HTML template for index page -->

{# python code between the following symbols #}
{% extends 'music/base.html' %}
{# that was indicating that we are using the base template here #}
{# also python comments are written like this #}

{# this is the block used in head for the title in base.html #}
{% block title %}
    <title>Music</title>
{% endblock %}

{# this is the block used in li elements in nav in base.html #}
{# NOTE: fix this, doesn't work #}
{% block album_active_active %}active{% endblock %}


{# this is the block used after nav in the body in base.html #}
{% block body %}
    <div class="albums-container container-fluid">

        <!-- Albums -->
        <div class="row">
            <div class="col-sm-12">
                <h3>{{ user.username }}'s Albums</h3>
            </div>
            {# object list is default name for the get_queryset function in views, it was changed to all_albums later #}
            {% if all_albums %}
                <ul>
                    {% for album in all_albums %}
                        <div class="col-sm-4 col-lg-2">
                            <div class="thumbnail">
                                {# python variable inside the double curly brackets #}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                                <div class="caption">
                                    <h2>{{ album.album_title }}</h2>
                                    <h4>{{ album.artist }}</h4>

                                    <!-- View Details -->
                                    <!-- indicates that url is for the music app, the detail url and pk is album.id -->
                                    <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm"
                                       role="button">View Details</a>

                                    <!-- Delete Album -->
                                    <form action="{% url 'music:album-delete' album.id %}" method="post"
                                          style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>

                                </div>
                            </div>
                        </div>

                        {# styling things #}
                        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                        {# we must close the python for loop #}
                    {% endfor %}
                </ul>
            {% else %}
                <div class="col-sm-12">
                    <br>
                    <a href="{% url 'music:album-add' %}">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                        </button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}﻿

music/templates/music/registration_form.html
<!-- modified code from album_form.html -->

{# python code between the following symbols #}
{%  extends 'music/base.html' %}
{# that was indicating that we are using the base template here #}
{# also python comments are written like this #}

{# this is the block used in head for the title in base.html #}
{% block title %}
    <title>Register</title>
{% endblock %}

{# this is the block used after nav in the body in base.html #}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a New Account</h3>
                        <!-- making a form for creating a new album -->
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {# adding the security token #}
                            {% csrf_token %}
                            {# including the generic form template #}
                            {% include 'music/form-template.html' %}

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}